### ISSUE TITLE
Rich Results for certain pages

### ISSUE THREAD

**Issue by Henri-K** [Miralaw/thistoo-marketing#10]
http://ogp.me/#types

- [ ] research rich results (reference https://developers.google.com/custom-search/docs/snippets)
- [ ] Identify pages
- [ ] plan execution phase
- [ ] add bing suggestions for markup improvements https://www.bing.com/webmaster/help/marking-up-your-site-with-structured-data-3a93e731

**Comment by mathewsonke** [comment]
# Findings:
- The SEO benefit of the OG protocol is limited. 
- The google resource linked above is for Google Custom Search (implementing a sitewide google search to your site).
- Rich snippets appear to affect *visibility* of results moreso than their SEO ranking. Still worth approaching

# Google
**Resource** - https://developers.google.com/search/docs/guides/mark-up-content
** Formats ** - JSON-LD (recommended), Microdata, RDFa
** Benefit ** - Only really useful for tagging our AMP pages, which may be why we aren't in the carousel. Also minor things like breadcrumbs

# Bing 
**Resource** - https://www.bing.com/webmaster/help/marking-up-your-site-with-structured-data-3a93e731
** Formats ** - Microdata/Schema.org, Microformats, RDFa, OpenGraph (poorly supported)
** Benefit ** - Rich snippets similar to google

# Facebook
**Resource** - https://developers.facebook.com/docs/sharing/webmasters#markup
** Formats ** - OpenGraph
** Benefit ** - Define the content shown when a page is shared to Facebook

# Plan
- Discuss with Henri on monday what we should implement
- Create issue for implementation of rich snippets
