### ISSUE TITLE
Make infographics stylistically consistent 

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#17]
Compile all of our infographics and make them consistent with Thistoo style/branding (refer to style guide)

- [x] divorce process
- [x] divorce task list
- [x] free tools: support calculator
- [ ] guide to uncontested divorce: individual graphics per step to breakdown tasks for easier understanding
- [x] Heal after divorce tips: compile into one
- [ ] (optional) navigating the holidays
- [x] matrimonial home
- [ ] parenting plan

**Comment by Henri-K** [comment]
here are some commnents for the infographics @claru049:
- i combined all graphics into a single file: infographics_v2, it's easier to compare and match styling, sizing, etc.
- there's now a document colour palette for our brand colours
- i added some rectangle spacers to make sure the styling is consistent
- i added a variety of text styles

can you please go over all artboards and convert/adapt the styles so they are consistent?

**Comment by Henri-K** [comment]
@claru049 

create/simplify vectors of the following icons:
- [ ] airplane
- [ ] medial
- [ ] thumbs up
- [ ] religion
- [ ] unique issues -> add questions mark inside star
