### ISSUE TITLE
Adwords keyword review

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#23]
https://adwords.google.com/ko/KeywordPlanner/Home?__u=6715439272&__c=7124894512&authuser=0#start

- [x] identify poor performers
- [x] identify untapped/unused new keywords
- [x] implement changes
- [x] track changes (and date)

**Comment by claru049** [comment]
@bennett-brown I deleted the duplicates should we close this issue and just have a new one for tracking changes since the other improvements are accounted for in other issues?

**Comment by bennett-brown** [comment]
@claru049 

1) remove duplicates - [ ] 
2) create new issue for review of changes
3) Ad text alterations will become part of isseue #30 
4) we will revisit budget experimentation after all other current changes have been implemented and reviewed
