### ISSUE TITLE
Build out ad groups

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#30]
As per google consultant advice, we need to build out our ad groups to 3-5 ads per ad group

- [x] support calculator
- [x] divorce documents
- [x] general divorce
- [x] alt divorce
- [x] file / apply for divorce
- [x] record baseline measurements for each (CPC,CTR,COC,AVG.POS)

**Comment by bennett-brown** [comment]
https://docs.google.com/spreadsheets/d/1GTGWCQ1Yq4-p1KB7wf1AACgVUnzl55kwx0-1Yu7lNa8/edit#gid=296016007

**Comment by claru049** [comment]
Waiting for clarification from google as to why some of the ads were disapproved.

**Comment by claru049** [comment]
Mistake on googles part all of the ads have now been approved
