### ISSUE TITLE
Build a collection of user stories

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#44]
map out all of the different routes that users take as they navigate through our webapp

- [x] build personas (at least 2 / pillar, x 4 pillars for a total of 8 - can make more at your discretion)
- [x] drive each persona through the app as appropriate, carefully document the entire process
- [x] make sure to include different acquisition pathways (how do they arrive? search? adwords? blog - different pathways may require different stories/personas)
- [x] summarize findings into a report
- [x] Review

**Comment by claru049** [comment]
Here is the report: https://docs.google.com/document/d/1t-TM6NE6etmNfkRhalUlCq4N8Fn8iTWxlfurM1NhoZM/edit#heading=h.z47qiecim0qv

**Comment by bennett-brown** [comment]
compile with #51 into report on key takeaways/actionable items
