### ISSUE TITLE
Drip campaign email improvements

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#5]
refer to #14 for guidance in determining which emails to improve

- [x] identify 3 worst performing emails (CTR)
- [x] integrate existing infographics to improve under performers
- [x] remove john from all emails
- [ ] Review  text changes (any that say they were updated in the last 48hrs) 
- [ ] track results (ongoing)

**Comment by bennett-brown** [comment]
Change of focus - retool all of the "free emails" for better user engagement and onboarding

**Comment by bennett-brown** [comment]
https://docs.google.com/spreadsheets/d/1Lnk6cndz4NZw_3NjgQNXLR4TrWZBKcxsLgo5bWBhCFM/edit#gid=0

**Comment by Henri-K** [comment]
@bennett-brown can you review the copy on the infographics `healing_after_divorce`, `matrimonial_home` -> the cta on the bottom in particular, `uncontested_divorce` -> shrunk down the steps

**Comment by bennett-brown** [comment]
@Henri-K @claru049 - looks pretty good, one thing the final step in uncontested divorce is formatted strangely and seems to be uneditable?

<img width="296" alt="screen shot 2017-03-07 at 4 14 39 pm" src="https://cloud.githubusercontent.com/assets/16229730/23678217/2eb01f2e-0351-11e7-91f9-23a973c7e04a.png">

**Comment by Henri-K** [comment]
@bennett-brown you were missing the fonts. it looks fine for us. Thank you for the typo fixes. @claru049 will adjust the `divorce certificate` block to be on two lines and the content properly spaced.

**Comment by bennett-brown** [comment]
@claru049 integration phase:

1)match each infographic to the topically relevant campaign (example: the divorce application process infographic would belong to the divorce application email campaign)
2) identify the lowest performer in each campaign based on CTR
3) change the email content to utilize the infographic with a clear call to action
4) track with new comment (campaign, emailed changed, baseline CTR, date changed)

**Comment by claru049** [comment]
@bennett-brown @Henri-K I integrated the infographics into the relevant emails with less than 5% CTR. This only ended up being 8 emails, they all linked to the blog, and the free tools and healing after divorce graphics weren't used. Should I expand to target emails with higher CTR or should we wait and see how these ones perform first?
This document has all the changes and CTR's recorded: https://docs.google.com/document/d/1NBT5FZk6lNg5y2Ej7c1RHsXeKQufUa2pNquqW2h6mlo/edit#heading=h.9g3oy4gxknlo

**Comment by claru049** [comment]
+4 points for text changes
