### ISSUE TITLE
market research through observation

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#51]
- [x] recruit at least 3 friends / family (5 would be ideal)
- [x] give them some sort of purpose but minimal instruction (crafting a persona may be helpful)
- [x] carefully document their experience using the app (step by step process, note all questions or roadblocks/frustrations) be careful not to give too much instruction (try to replicate an organic experience)
- [x] write a report summarizing findings (including, but not limited to, commonalities, blocks, errors, things they liked, things that didnt make sense etc)
- [x] Review

**Comment by claru049** [comment]
Here is the report: https://docs.google.com/document/d/1Mn6hRV-1vA-UYH4VY3cdKsbYYN_JMbUf-QP7eC6mj08/edit#
