### ISSUE TITLE
Build asset calculator adwords campaign

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#61]
Build a campaign around asset calculator feature (campaign, keyword compilation, 3-5 ads)

**Comment by claru049** [comment]
@bennett-brown Proposal: https://docs.google.com/document/d/1-rpMG4VB7bVgU4f52l2md3LpozBjOP-L5zoIJiBscYU/edit#

**Comment by bennett-brown** [comment]
Build out ads in adwords interface for next review
