### ISSUE TITLE
Blog post may 12

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#84]
- [x] Research and choose topic
- [x] Write draft
- [x] Format in squarespace
- [x] Review
- [x] Make corrections
 - [x] Post and boost

**Comment by gabrielladifazio** [comment]
[MiralawBlog1.docx](https://github.com/Miralaw/thistoo-marketing/files/987143/MiralawBlog1.docx)
here is my draft for the blog on friday, I had a couple questions regarding it (some of them are indicated in it) that I wanted to discuss but they are not urgent
